## Milestone 1

- Nama  : Putri Joeliya
- Batch : CODA-RMT-020


program ini di buat melakukan proses scraping terhadap website game digital 'steam' membuatnya menjadi data frame berdasarkan nama game, harga, taring, released, dan developer.
untuk selajutnya data tersebut akan di bersihkan dan di unggah ke sql dan akan di normalisasi kembali seluruh datanya.

In [ ]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By 
from bs4 import BeautifulSoup
import time 

names = []
prices = []
ratings = []
released = []
publishers = []

#meminta driver untuk membuka web 
driver = webdriver.Chrome()
url = 'https://store.steampowered.com/category/action_fps'
driver.get(url)
time.sleep(30)

#melakukan scrolling untuk memuat data, karena sistem website steam tidak memiliki page sehingga perlu dilakukannya scrolling untuk memuat lebih banyak data 
for i in range(1, 15):
    jarak_scroll = i * 1000
    driver.execute_script(f"window.scrollTo(0, {jarak_scroll});")
    print(f"posisi {jarak_scroll}px")
    time.sleep(10)

driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
time.sleep(10)

soup = BeautifulSoup(driver.page_source, 'html.parser')

#melakukan boxes untuk mengambil data yang diinginkan, karena data yang diambil memiliki class yang sama sehingga perlu dilakukan box untuk mengambil data yang diinginkan
boxes = soup.find_all('div', {'class' : '_2hhNOdcC6yLwL_rugP3YLf PZY_7wH_NY7OgzH9MBiB8 LibraryAssetExpandedDisplay'})

#melakukan try except untuk mengambil data yang diinginkan, ini gunakan agar data data yang tidak memiliki isi tetap bisa diambil dan tidak error, sehingga data yang diambil tetap lengkap
for box in boxes:
    try:
        nama = box.find('img', {'class' : '_2eQ4mkpf4IzUp1e9NnM2Wr'}).get('alt')
        names.append(nama)
    except:
        names.append('None')    
    
    try:
        harga = box.find('div', {'class' : '_3j4dI1yA7cRfCvK8h406OB'}).get_text()
        prices.append(harga)
    except:
        prices.append('None')
    try:
        rating = box.find('div', {'class' : 'uEsfJ0VAuX37ItihZkK2J'}).get_text()
        ratings.append(rating)
    except:
        ratings.append('None')
    try:
        release = box.find('div', {'class' : 'vCEpeeiHJkcIDdtTkRfjT'}).get_text()
        released.append(release)
    except:
        released.append('None')
    try:
        publisher = box.find('div', {'class' : '_3tIbO7JWeYXTD8fDol5_-f'}).get_text()
        publishers.append(publisher)
    except:
        publishers.append('None')

time.sleep(10)
driver.quit()

posisi 1000px
posisi 2000px
posisi 3000px
posisi 4000px
posisi 5000px
posisi 6000px
posisi 7000px
posisi 8000px
posisi 9000px
posisi 10000px
posisi 11000px
posisi 12000px
posisi 13000px
posisi 14000px

In [ ]:
#pengecakan jumlah data yang di ambil untuk memastikan apakah sudah sesuai dengan kebutuhan jumlah data 
print(len(names))
print(len(prices))
print(len(ratings))
print(len(released))
print(len(publishers))

60
60
60
60
60

In [ ]:
#membuat data frame terhadap data yang sudah di scraping, agar data yang diambil bisa diolah lebih lanjut
df = pd.DataFrame({
    'Name' : names,
    'Price' : prices,
    'Rating' : ratings,
    'Release Date' : released,
    'Developer' : publishers
})

df

,Name,Price,Rating,Release Date,Developer
0,Apex Legends™,Free To Play,Mostly Positive,Release date: 5 Nov 2020,Developed By:Respawn
1,Counter-Strike 2,Free To Play,Very Positive,Release date: 22 Aug 2012,Developed By:Valve
2,PUBG: BATTLEGROUNDS,Free To Play,Mixed,Release date: 21 Dec 2017,Developed By:PUBG Corporation
3,Overwatch®,Free To Play,Mostly Negative,Release date: 11 Aug 2023,"Developed By:Blizzard Entertainment, Inc."
4,Grand Theft Auto V Enhanced,Rp 219 500,Very Positive,Release date: 4 Mar 2025,Developed By:Rockstar North
5,Call of Duty®: Modern Warfare® II,Rp 104 000,Mostly Negative,Release date: 23 Oct 2022,Developed By:Infinity Ward
6,Cyberpunk 2077: Phantom Liberty,Rp 209 999,Very Positive,Release date: 26 Sept 2023,Developed By:CD PROJEKT RED
7,SAND: Raiders of Sophie,Rp 94 799,Mixed,Release date: 23 Jun 2026,Developed By:Hologryph
8,Ready or Not,Rp 127 999,Mostly Positive,Release date: 14 Dec 2023,Developed By:VOID Interactive
9,Arena Breakout: Infinite,Free To Play,Mostly Positive,Release date: 16 Sept 2025,Developed By:Morefun Studios
10,Destiny 2,Free To Play,Mostly Positive,Release date: 2 Oct 2019,Developed By:Bungie
11,Rust,Rp 164 500,Very Positive,Release date: 9 Feb 2018,Developed By:Facepunch Studios
12,Battlefield™ 6,Rp 399 500,Mixed,Release date: 10 Oct 2025,Developed By:Battlefield Studios
13,Escape from Tarkov,Rp 243 749,Mixed,Release date: 15 Nov 2025,Developed By:Battlestate Games
14,Delta Force,Free To Play,Mixed,Release date: 5 Dec 2024,Developed By:Team Jade
15,Tom Clancy's Rainbow Six Siege,Free To Play,Very Positive,Release date: 2 Dec 2015,Developed By:Ubisoft Montreal
16,Call of Duty®: Black Ops III,Rp 294 030,Very Positive,Release date: 6 Nov 2015,Developed By:Treyarch
17,Fallout 76,Rp 133 000,Mostly Positive,Release date: 15 Apr 2020,Developed By:Bethesda Game Studios
18,Call of Duty®: Black Ops 7,Rp 499 500,Mostly Negative,Release date: 14 Nov 2025,Developed By:Treyarch
19,Far Cry® 4,Rp 30 900,Very Positive,Release date: 18 Nov 2014,"Developed By:Ubisoft Montreal, Red Storm, Shan..."
20,Call of Duty®: Black Ops II,Rp 197 670,Very Positive,Release date: 12 Nov 2012,Developed By:Treyarch
21,DOOM: The Dark Ages,Rp 329 999,Very Positive,Release date: 15 May 2025,Developed By:id Software
22,Team Fortress 2,Free To Play,Very Positive,Release date: 10 Oct 2007,Developed By:Valve
23,Metro Exodus,Rp 32 100,Very Positive,Release date: 15 Feb 2020,Developed By:4A Games
24,Avatar: Frontiers of Pandora™,Rp 209 400,Mostly Positive,Release date: 18 Jun 2024,Developed By:Massive Entertainment – A Ubisoft...
25,Arma Reforger,Rp 349 999,Mostly Positive,Release date: 16 Nov 2023,Developed By:Bohemia Interactive
26,DayZ,Rp 324 999,Mostly Positive,Release date: 14 Dec 2018,Developed By:Bohemia Interactive
27,MOUSE: P.I. For Hire,Rp 196 799,Very Positive,Release date: 16 Apr 2026,Developed By:Fumi Games
28,Halo: Campaign Evolved,Rp 799 000,None,"Release date: Jul 28, 2026",Developed By:Halo Studios
29,Far Cry® 5,Rp 92 850,Very Positive,Release date: 27 Mar 2018,Developed By:Ubisoft Montreal
30,S.T.A.L.K.E.R. 2: Heart of Chornobyl,Rp 465 500,Mostly Positive,Release date: 20 Nov 2024,Developed By:GSC Game World
31,Left 4 Dead 2,Rp 18 199,Overwhelmingly Positive,Release date: 17 Nov 2009,Developed By:Valve
32,Gray Zone Warfare,Rp 326 960,Mostly Positive,Release date: 30 Apr 2024,"Developed By:MADFINGER Games, a.s."
33,Call of Duty®: Modern Warfare® 4,Rp 999 000,None,"Release date: Oct 23, 2026",Developed By:Infinity Ward
34,Hunt: Showdown 1896,Rp 102 000,Mostly Positive,Release date: 27 Aug 2019,Developed By:Crytek
35,Destiny 2: Renegades,Rp 126 499,Mixed,Release date: 3 Dec 2025,Developed By:Bungie
36,Battlefield™ REDSEC,Free To Play,Mixed,Release date: 28 Oct 2025,Developed By:Battlefield Studios
37,Squad,Rp 210 400,Very Positive,Release date: 24 Sept 2020,Developed By:Offworld
38,PAYDAY 2,Rp 25 350,Very Positive,Release date: 13 Aug 2013,Developed By:OVERKILL - a Starbreeze Studio.
39,Call of Duty®: Warzone™,Free To Play,Mostly Negative,Release date: 17 Nov 2022,Developed By:Infinity Ward
40,Far Cry® 6,Rp 154 750,Mixed,Release date: 11 May 2023,Developed By:Ubisoft Toronto
41,Witchfire,Rp 239 999,Very Positive,Release date: 23 Sept 2024,Developed By:The Astronauts
42,Fallout 4,Rp 106 400,Very Positive,Release date: 10 Nov 2015,Developed By:Bethesda Game Studios
43,Marathon,Rp 314 999,Very Positive,Release date: 6 Mar 2026,Developed By:Bungie
44,Garry's Mod,Rp 44 999,Overwhelmingly Positive,Release date: 30 Nov 2006,Developed By:Facepunch Studios
45,ULTRAKILL,Rp 108 749,Overwhelmingly Positive,Release date: 3 Sept 2020,Developed By:Arsi &quot;Hakita&quot; Patala
46,Far Far West,Rp 123 299,Overwhelmingly Positive,Release date: 28 Apr 2026,Developed By:Evil Raptor
47,Destiny 2: The Edge of Fate,Rp 92 000,Mostly Negative,Release date: 16 Jul 2025,Developed By:Bungie
48,Call of Duty®: Black Ops,Rp 299 500,Very Positive,Release date: 9 Nov 2010,Developed By:Treyarch
49,MechWarrior 5: Mercenaries,Rp 34 999,Very Positive,Release date: 27 May 2021,Developed By:Piranha Games Inc.
50,World War Z,Rp 64 750,Very Positive,Release date: 21 Sept 2021,Developed By:Saber Interactive Inc
51,Bodycam,Rp 227 999,Mostly Positive,Release date: 8 Jun 2024,Developed By:Reissad Studio
52,World of Tanks Blitz,Free To Play,Mostly Positive,Release date: 9 Nov 2016,Developed By:Wargaming Group Limited
53,Call of Duty®: Modern Warfare®,Rp 294 030,Very Positive,Release date: 9 Mar 2023,Developed By:Infinity Ward
54,THE FINALS,Free To Play,Very Positive,Release date: 8 Dec 2023,Developed By:Embark Studios
55,Metro 2033 Redux,Rp 10 700,Very Positive,Release date: 28 Aug 2014,Developed By:4A Games
56,Battlefield™ V,Rp 28 450,Mostly Positive,Release date: 22 Oct 2020,Developed By:DICE
57,OPERATOR,Rp 111 219,Very Positive,Release date: 1 Aug 2023,Developed By:VECTOR INTERACTIVE PTY LTD
58,Deep Rock Galactic,Rp 56 700,Overwhelmingly Positive,Release date: 13 May 2020,Developed By:Ghost Ship Games
59,Aimlabs,Free To Play,Very Positive,Release date: 17 Jun 2023,Developed By:Statespace

In [ ]:
#proses membersihkan data yang sudah di ambil tetapi bentuknya masih berantakan 

#menghilangkan kata "Release date: " agar lebih rapih dalam tabel
df['Release Date'] = df['Release Date'].str.replace('Release date: ', '', case=False)

#menghilangkan kata "Developed By:" agar lebih rapih dalam tabel
df['Developer'] = df['Developer'].str.replace('Developed By:', '', case=False)

df['Release Date'] = df['Release Date'].str.strip()
df['Developer'] = df['Developer'].str.strip()

#beberapa data di dalam release date perlru di modifikasi karna penataan tanggalnya berantakan di dalam tabel.
df['Release Date'] = df['Release Date'].str.replace('Release date: ', '', case=False)
df['Release Date'] = df['Release Date'].str.strip()
df['Release Date'] = df['Release Date'].str.replace('SEPT', 'Sep', case=False)
df['Release Date'] = pd.to_datetime(df['Release Date'], format='mixed', errors='coerce')


df

,Name,Price,Rating,Release Date,Developer
0,Apex Legends™,Free To Play,Mostly Positive,2020-11-05,Respawn
1,Counter-Strike 2,Free To Play,Very Positive,2012-08-22,Valve
2,PUBG: BATTLEGROUNDS,Free To Play,Mixed,2017-12-21,PUBG Corporation
3,Overwatch®,Free To Play,Mostly Negative,2023-08-11,"Blizzard Entertainment, Inc."
4,Grand Theft Auto V Enhanced,Rp 219 500,Very Positive,2025-03-04,Rockstar North
5,Call of Duty®: Modern Warfare® II,Rp 104 000,Mostly Negative,2022-10-23,Infinity Ward
6,Cyberpunk 2077: Phantom Liberty,Rp 209 999,Very Positive,2023-09-26,CD PROJEKT RED
7,SAND: Raiders of Sophie,Rp 94 799,Mixed,2026-06-23,Hologryph
8,Ready or Not,Rp 127 999,Mostly Positive,2023-12-14,VOID Interactive
9,Arena Breakout: Infinite,Free To Play,Mostly Positive,2025-09-16,Morefun Studios
10,Destiny 2,Free To Play,Mostly Positive,2019-10-02,Bungie
11,Rust,Rp 164 500,Very Positive,2018-02-09,Facepunch Studios
12,Battlefield™ 6,Rp 399 500,Mixed,2025-10-10,Battlefield Studios
13,Escape from Tarkov,Rp 243 749,Mixed,2025-11-15,Battlestate Games
14,Delta Force,Free To Play,Mixed,2024-12-05,Team Jade
15,Tom Clancy's Rainbow Six Siege,Free To Play,Very Positive,2015-12-02,Ubisoft Montreal
16,Call of Duty®: Black Ops III,Rp 294 030,Very Positive,2015-11-06,Treyarch
17,Fallout 76,Rp 133 000,Mostly Positive,2020-04-15,Bethesda Game Studios
18,Call of Duty®: Black Ops 7,Rp 499 500,Mostly Negative,2025-11-14,Treyarch
19,Far Cry® 4,Rp 30 900,Very Positive,2014-11-18,"Ubisoft Montreal, Red Storm, Shanghai, Toronto..."
20,Call of Duty®: Black Ops II,Rp 197 670,Very Positive,2012-11-12,Treyarch
21,DOOM: The Dark Ages,Rp 329 999,Very Positive,2025-05-15,id Software
22,Team Fortress 2,Free To Play,Very Positive,2007-10-10,Valve
23,Metro Exodus,Rp 32 100,Very Positive,2020-02-15,4A Games
24,Avatar: Frontiers of Pandora™,Rp 209 400,Mostly Positive,2024-06-18,Massive Entertainment – A Ubisoft Studio
25,Arma Reforger,Rp 349 999,Mostly Positive,2023-11-16,Bohemia Interactive
26,DayZ,Rp 324 999,Mostly Positive,2018-12-14,Bohemia Interactive
27,MOUSE: P.I. For Hire,Rp 196 799,Very Positive,2026-04-16,Fumi Games
28,Halo: Campaign Evolved,Rp 799 000,None,2026-07-28,Halo Studios
29,Far Cry® 5,Rp 92 850,Very Positive,2018-03-27,Ubisoft Montreal
30,S.T.A.L.K.E.R. 2: Heart of Chornobyl,Rp 465 500,Mostly Positive,2024-11-20,GSC Game World
31,Left 4 Dead 2,Rp 18 199,Overwhelmingly Positive,2009-11-17,Valve
32,Gray Zone Warfare,Rp 326 960,Mostly Positive,2024-04-30,"MADFINGER Games, a.s."
33,Call of Duty®: Modern Warfare® 4,Rp 999 000,None,2026-10-23,Infinity Ward
34,Hunt: Showdown 1896,Rp 102 000,Mostly Positive,2019-08-27,Crytek
35,Destiny 2: Renegades,Rp 126 499,Mixed,2025-12-03,Bungie
36,Battlefield™ REDSEC,Free To Play,Mixed,2025-10-28,Battlefield Studios
37,Squad,Rp 210 400,Very Positive,2020-09-24,Offworld
38,PAYDAY 2,Rp 25 350,Very Positive,2013-08-13,OVERKILL - a Starbreeze Studio.
39,Call of Duty®: Warzone™,Free To Play,Mostly Negative,2022-11-17,Infinity Ward
40,Far Cry® 6,Rp 154 750,Mixed,2023-05-11,Ubisoft Toronto
41,Witchfire,Rp 239 999,Very Positive,2024-09-23,The Astronauts
42,Fallout 4,Rp 106 400,Very Positive,2015-11-10,Bethesda Game Studios
43,Marathon,Rp 314 999,Very Positive,2026-03-06,Bungie
44,Garry's Mod,Rp 44 999,Overwhelmingly Positive,2006-11-30,Facepunch Studios
45,ULTRAKILL,Rp 108 749,Overwhelmingly Positive,2020-09-03,Arsi &quot;Hakita&quot; Patala
46,Far Far West,Rp 123 299,Overwhelmingly Positive,2026-04-28,Evil Raptor
47,Destiny 2: The Edge of Fate,Rp 92 000,Mostly Negative,2025-07-16,Bungie
48,Call of Duty®: Black Ops,Rp 299 500,Very Positive,2010-11-09,Treyarch
49,MechWarrior 5: Mercenaries,Rp 34 999,Very Positive,2021-05-27,Piranha Games Inc.
50,World War Z,Rp 64 750,Very Positive,2021-09-21,Saber Interactive Inc
51,Bodycam,Rp 227 999,Mostly Positive,2024-06-08,Reissad Studio
52,World of Tanks Blitz,Free To Play,Mostly Positive,2016-11-09,Wargaming Group Limited
53,Call of Duty®: Modern Warfare®,Rp 294 030,Very Positive,2023-03-09,Infinity Ward
54,THE FINALS,Free To Play,Very Positive,2023-12-08,Embark Studios
55,Metro 2033 Redux,Rp 10 700,Very Positive,2014-08-28,4A Games
56,Battlefield™ V,Rp 28 450,Mostly Positive,2020-10-22,DICE
57,OPERATOR,Rp 111 219,Very Positive,2023-08-01,VECTOR INTERACTIVE PTY LTD
58,Deep Rock Galactic,Rp 56 700,Overwhelmingly Positive,2020-05-13,Ghost Ship Games
59,Aimlabs,Free To Play,Very Positive,2023-06-17,Statespace

In [ ]:
#memuat informasi di dalam data frame 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          60 non-null     object
 1   Price         60 non-null     object
 2   Rating        60 non-null     object
 3   Release Date  60 non-null     datetime64[ns]
 4   Developer     60 non-null     object
dtypes: datetime64[ns](1), object(4)
memory usage: 2.5+ KB

pada data frame terdapat:
1. 5 kolom dan 60 baris (data total 60) index 0-59
2. dengan masing masing kolom merupakan:
    - name = nama game 
    - price = harga game > beberapa game memang tidak berbayar dengan keterangan 'free to play' atau 'free demo' 
    - rating = kategori rating setiap game 
    - release date = tanggal dimana game di terbitkan 
    - developer = perusahaan tempat game tersebut di develop 
3. memiliki Dtype dengan jenis object sebanyak 5 dan datetime64[ns] sebanyak 
  
    ps. unutk harga dan rating tidak bisa di ubah kedalam integer karena beberapa produk memiliki keterangan selain angka

In [ ]:
#membuat sample data untuk melihat data yang sudah di ambil dan diolah
sample = df.head()
sample

,Name,Price,Rating,Release Date,Developer
0,Apex Legends™,Free To Play,Mostly Positive,2020-11-05,Respawn
1,Counter-Strike 2,Free To Play,Very Positive,2012-08-22,Valve
2,PUBG: BATTLEGROUNDS,Free To Play,Mixed,2017-12-21,PUBG Corporation
3,Overwatch®,Free To Play,Mostly Negative,2023-08-11,"Blizzard Entertainment, Inc."
4,Grand Theft Auto V Enhanced,Rp 219 500,Very Positive,2025-03-04,Rockstar North

In [ ]:
#mengimpor data menjadi .csv agar bisa di olah kembali di dalam SQL
df.to_csv('coda_P0M1_Putri_Joeliya.csv', index=False)